### ISSUE TITLE
[BUG] “上网习惯”页面只显示顶部区域不显示下方内容

### ISSUE THREAD

**Issue by Yiiip** [sheepzh/timer#245]
## Tell me the environment / 请先填写版本信息

Version: v2.0.1
OS: Win10
Browser: Microsoft Edge 120.0.2210.61 (正式版本) (64 位)

## Detail / Bug 详情

“上网习惯”页面只显示顶部区域，不显示下方内容。
```
vue.js:2  TypeError: Cannot read properties of undefined (reading 'startTime')
    at app.js:2:179435
    at app.js:2:179820
    at e.render (app.js:2:180916)
    at Proxy.render (app.js:2:178195)
    at app.js:2:183671
    at app.js:2:353922
    at Object.next (app.js:2:354027)
    at a (app.js:2:352745)
(anonymous) @ vue.js:2
app.js:2  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startTime')
    at app.js:2:179435
    at app.js:2:179820
    at e.render (app.js:2:180916)
    at Proxy.render (app.js:2:178195)
    at app.js:2:183671
    at app.js:2:353922
    at Object.next (app.js:2:354027)
    at a (app.js:2:352745)
```
![1](https://github.com/sheepzh/timer/assets/10251493/aa78c7ba-7ff7-45f5-87d4-d872279ad7fa)

**Comment by sheepzh** [comment]
感谢反馈，已紧急修复，预计一周内会通过 edge 商城审核
